[package]
name = "chess"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  "chess-core",
  "chess-server",
  "chess-client",
  "http-for-bevy"
]

[dependencies]
chess-server = { version = "0.1", path = "chess-server" }
dotenv = "0.15.0"
tokio = { version = "1.50.0", features = ["rt-multi-thread"] }

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
